{% set name = "asteval" %}
{% set version = "0.9.23" %}
{% set sha256 = "f5096a924b1d2f147e70327245d95fc8f534dbe94277b6828ce2a8c049d3a438" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - numpy
    - pip
    - six
  run:
    - python
    - numpy
    - six

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/newville/asteval
  license: BSD
  license_file: LICENSE
  summary: Simple and robust expressions evaluator for Python

  # The remaining entries in this section are optional, but recommended
  description: |
    asteval is a simple and robust evaluator of
    Python expressions and statements, using Python's ast module.
  doc_url: http://newville.github.io/asteval/
  dev_url: https://github.com/newville/asteval
